### ISSUE TITLE
 Operator '>' cannot be applied to operands of type 'System.Int64' and 'System.Int32'

### ISSUE THREAD

**Issue by Korayem** [jwaliszko/ExpressiveAnnotations#130]
In a new project, suddenly I can't write the following
```
        [AssertThat("StudentId > 0", ErrorMessage = "Please select a Student")]
        public long StudentId { get; set; }
```
EA is working perfectly in other projects in nuget version 2.5.1 but with nuget version 2.6.0 it's not

**Comment by Korayem** [comment]
Found this but not sure if it's related #63

**Comment by jwaliszko** [comment]
Indeed, regression error occurred in the last release. Will be fixed in new package. Thanks for reporting.

**Comment by jwaliszko** [comment]
Issue fixed here: https://github.com/jwaliszko/ExpressiveAnnotations/commit/dcfa4c9d3c04135758388773171a63acca1a54de.
It still requires few relevant unit tests to be covered by.

**Comment by Korayem** [comment]
@jwaliszko this fix is released as part of which nuget version?

**Comment by jwaliszko** [comment]
@Korayem: take latest, 2.9.1 (does some issue related to that still exists?).

**Comment by Korayem** [comment]
no no it works like a charm :)

Does https://www.nuget.org/packages/ExpressiveAnnotations.dll 2.6.0 equate
to 2.9.1?

On Tue, Sep 20, 2016 at 3:19 PM, Jarosław Waliszko <notifications@github.com

**Comment by jwaliszko** [comment]
No, [v2.9.1 product release](https://github.com/jwaliszko/ExpressiveAnnotations/releases/tag/v2.9.1) contains following components: 
* ExpressiveAnnotations.dll v2.7.0 (core annotations assembly), 
* ExpressiveAnnotations.MvcUnobtrusive.dll v2.5.1 (MVC validators assembly), 
* expressive.annotations.validate.js v2.6.8 (unobtrusive validation script).

[MVC package](https://www.nuget.org/packages/ExpressiveAnnotations/) contains all 3 components, so product version is always the same as the MVC package version. [Standalone package](https://www.nuget.org/packages/ExpressiveAnnotations.dll) contains only single component, mainly ExpressiveAnnotations.dll core annotations assembly. It is also mentioned in the [installation section](https://github.com/jwaliszko/ExpressiveAnnotations#installation) in the docummentation.

**Some more explanation:**

At the initial stage of working at this library I had been thinking of how to version the releases. At first I thought the highest version of all the components will automatically define the version of the package. But after a while I realized it is not always possible, and manual versioning is needed - example is below:
```
initial version ---> A.dll v1.0, B.dll v1.0, C.js v1.0 ---> release ---> NuGet package v1.0
bug fix for A   ---> A.dll v1.1, B.dll v1.0, C.js v1.0 ---> release ---> NuGet package v1.1
bug fix for B   ---> A.dll v1.1, B.dll v1.1, C.js v1.0 ---> release ---> NuGet package v?.? 
                                                                                (chosen 1.2)
bug fix for B   ---> A.dll v1.1, B.dll v1.2, C.js v1.0 ---> release ---> NuGet package v?.? 
                                                                                (chosen 1.3)
feature for C   ---> A.dll v1.1, B.dll v1.2, C.js v2.0 ---> release ---> NuGet package v?.? 
                                                                                (chosen 2.0)
```

Because many NuGet packages contain only single component, there is no discrepancy between the package version and such an component (assembly/script/etc.) version.

**Comment by Korayem** [comment]
I know the difference between EA and EA.dll but I didn't know about versioning schema you're following. I understand the predicament here :)
